"""Settings manager for Rotor Control.

Handles loading/saving configuration from INI and JSON files.
INI serves as factory defaults, JSON stores user overrides.
"""

import json
import sys
import configparser
import threading
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

def log(message: str) -> None:
    """Print message with timestamp prefix."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {message}", file=sys.stdout, flush=True)

# Complete default configuration with all UI-relevant values
DEFAULT_CONFIG = {
    # Connection
    "baudRate": 9600,
    "pollingIntervalMs": 1000,
    "simulation": False,
    
    # Coordinates
    "mapLatitude": None,
    "mapLongitude": None,
    "satelliteMapEnabled": False,
    "mapZoomLevel": 15,
    "mapZoomMin": 5,
    "mapZoomMax": 25,
    
    # Cone visualization
    "coneAngle": 10,
    "coneLength": 1000,
    "azimuthDisplayOffset": 0,
    "coneAngleMin": 1,
    "coneAngleMax": 90,
    "coneLengthMin": 0,
    "coneLengthMax": 100000,
    "azimuthDisplayOffsetMin": -180,
    "azimuthDisplayOffsetMax": 180,
    
    # Speed
    "azimuthSpeedDegPerSec": 4,
    "elevationSpeedDegPerSec": 2,
    "speedMinDegPerSec": 0.5,
    "speedMaxDegPerSec": 20,
    
    # Ramp (Soft Start/Stop PI controller)
    "rampEnabled": True,
    "rampKp": 0.4,
    "rampKi": 0.05,
    "rampSampleTimeMs": 400,
    "rampMaxStepDeg": 8,
    "rampToleranceDeg": 1.5,
    "rampKpMin": 0,
    "rampKpMax": 5,
    "rampKiMin": 0,
    "rampKiMax": 5,
    "rampSampleTimeMsMin": 100,
    "rampSampleTimeMsMax": 2000,
    "rampMaxStepDegMin": 0.1,
    "rampMaxStepDegMax": 45,
    "rampToleranceDegMin": 0.1,
    "rampToleranceDegMax": 10,
    
    # Mode
    "azimuthMode": 450,
    "elevationDisplayEnabled": True,
    
    # Limits
    "azimuthMinLimit": 0,
    "azimuthMaxLimit": 450,
    "elevationMinLimit": 0,
    "elevationMaxLimit": 90,
    
    # Calibration
    "azimuthOffset": 0,
    "elevationOffset": 0,
    "azimuthScaleFactor": 1.0,
    "elevationScaleFactor": 1.0,
    "azimuthScaleFactorMin": 0.1,
    "azimuthScaleFactorMax": 2.0,
    "elevationScaleFactorMin": 0.1,
    "elevationScaleFactorMax": 2.0,
}

# INI file template with sections and comments
DEFAULT_INI_TEMPLATE = """; Rotor Control Configuration
; This file is automatically generated
; Settings are organized by category

[Connection]
; Serial port connection settings
baudRate=9600
pollingIntervalMs=1000
simulation=false

[Coordinates]
; Map display coordinates
mapLatitude=null
mapLongitude=null
satelliteMapEnabled=false
mapZoomLevel=15
mapZoomMin=5
mapZoomMax=25

[Cone]
; Cone visualization settings
coneAngle=10
coneLength=1000
azimuthDisplayOffset=0
coneAngleMin=1
coneAngleMax=90
coneLengthMin=0
coneLengthMax=100000
azimuthDisplayOffsetMin=-180
azimuthDisplayOffsetMax=180

[Speed]
; Rotor movement speeds in degrees per second
azimuthSpeedDegPerSec=4
elevationSpeedDegPerSec=2
speedMinDegPerSec=0.5
speedMaxDegPerSec=20

[Ramp]
; Softstart/Softstop PI controller settings
rampEnabled=true
rampKp=0.4
rampKi=0.05
rampSampleTimeMs=400
rampMaxStepDeg=8
rampToleranceDeg=1.5
rampKpMin=0
rampKpMax=5
rampKiMin=0
rampKiMax=5
rampSampleTimeMsMin=100
rampSampleTimeMsMax=2000
rampMaxStepDegMin=0.1
rampMaxStepDegMax=45
rampToleranceDegMin=0.1
rampToleranceDegMax=10

[Mode]
; Azimuth rotation mode
azimuthMode=450
elevationDisplayEnabled=true

[Limits]
; Soft limits for rotor movement
azimuthMinLimit=0
azimuthMaxLimit=450
elevationMinLimit=0
elevationMaxLimit=90

[Calibration]
; Calibration offsets and scaling factors
azimuthOffset=0
elevationOffset=0
azimuthScaleFactor=1.0
elevationScaleFactor=1.0
azimuthScaleFactorMin=0.1
azimuthScaleFactorMax=2.0
elevationScaleFactorMin=0.1
elevationScaleFactorMax=2.0
"""


class SettingsManager:
    """Manages application settings from INI and JSON files."""
    
    def __init__(self, config_dir: Path):
        self.config_dir = config_dir
        self.ini_file = config_dir / "rotor-config.ini"
        self.json_file = config_dir / "web-settings.json"
        self.lock = threading.Lock()
        self.cache: Dict[str, Any] = {}
        self._load()

    def _generate_default_ini(self) -> None:
        """Generate default INI file with all required values."""
        try:
            with open(self.ini_file, 'w', encoding='utf-8') as f:
                f.write(DEFAULT_INI_TEMPLATE)
            log(f"[Settings] Generated default INI: {self.ini_file}")
        except Exception as e:
            log(f"[Settings] Error generating default INI: {e}")

    def _load(self):
        """Load all settings into cache."""
        with self.lock:
            # Start with defaults
            self.cache = DEFAULT_CONFIG.copy()
            
            # 1. Generate INI if missing
            if not self.ini_file.exists():
                log(f"[Settings] INI file not found, generating defaults...")
                self._generate_default_ini()
            
            # 2. Load INI (Base Hardware Config)
            ini_config = {}
            parser = configparser.ConfigParser()
            try:
                parser.read(self.ini_file, encoding="utf-8")
                for section in parser.sections():
                    for key, value in parser.items(section):
                        # Attempt typed conversion
                        try:
                            if value.lower() == 'true':
                                val = True
                            elif value.lower() == 'false':
                                val = False
                            elif value.lower() == 'null':
                                val = None
                            elif '.' in value:
                                val = float(value)
                            else:
                                val = int(value)
                        except:
                            val = value
                        ini_config[key] = val
            except Exception as e:
                log(f"[Settings] Error loading INI: {e}")

            # 3. Load JSON (Web/User Overrides)
            json_config = {}
            if self.json_file.exists():
                try:
                    with open(self.json_file, 'r', encoding='utf-8') as f:
                        json_config = json.load(f)
                except Exception as e:
                    log(f"[Settings] Error loading JSON: {e}")

            # Merge: defaults -> INI -> JSON (JSON has highest priority)
            self.cache.update(ini_config)
            self.cache.update(json_config)

    def get_all(self) -> Dict[str, Any]:
        """Get all settings as a dictionary."""
        with self.lock:
            return self.cache.copy()

    def update(self, new_settings: Dict[str, Any]):
        """Update settings and save to JSON."""
        with self.lock:
            self.cache.update(new_settings)
            
            # Save to JSON for persistence
            try:
                with open(self.json_file, 'w', encoding='utf-8') as f:
                    json.dump(self.cache, f, indent=2)
            except Exception as e:
                log(f"[Settings] Error saving JSON: {e}")
