"""Default configuration values for the rotor control application.

Contains all default settings and the INI template for configuration files.
"""

# Complete default configuration with all UI-relevant values
DEFAULT_CONFIG = {
    # Connection
    "baudRate": 9600,
    "pollingIntervalMs": 1000,
    "portPath": None,
    
    # Coordinates/Map
    "mapLatitude": None,
    "mapLongitude": None,
    "satelliteMapEnabled": False,
    "mapZoomLevel": 15,
    "mapZoomMin": 5,
    "mapZoomMax": 25,
    
    # Cone visualization
    "coneAngle": 10,
    "coneLength": 1000,
    "azimuthDisplayOffset": 0,
    "coneAngleMin": 1,
    "coneAngleMax": 90,
    "coneLengthMin": 0,
    "coneLengthMax": 100000,
    "azimuthDisplayOffsetMin": -180,
    "azimuthDisplayOffsetMax": 180,
    
    # Speed
    "azimuthSpeedDegPerSec": 4,
    "elevationSpeedDegPerSec": 2,
    "speedMinDegPerSec": 0.5,
    "speedMaxDegPerSec": 20,
    
    # ERC-DUO Speed Stages
    "azimuthLowSpeedStage": 3,
    "azimuthHighSpeedStage": 4,
    "elevationLowSpeedStage": 3,
    "elevationHighSpeedStage": 4,
    "azimuthSpeedAngleCode": 3,
    "elevationSpeedAngleCode": 3,
    
    # Ramp (Soft Start/Stop PI controller)
    "rampEnabled": False,
    "rampKp": 0.4,
    "rampKi": 0.05,
    "rampSampleTimeMs": 400,
    "rampMaxStepDeg": 8,
    "rampToleranceDeg": 1.5,
    "rampKpMin": 0,
    "rampKpMax": 5,
    "rampKiMin": 0,
    "rampKiMax": 5,
    "rampSampleTimeMsMin": 100,
    "rampSampleTimeMsMax": 2000,
    "rampMaxStepDegMin": 0.1,
    "rampMaxStepDegMax": 45,
    "rampToleranceDegMin": 0.1,
    "rampToleranceDegMax": 10,
    
    # Mode
    "azimuthMode": 450,
    "elevationDisplayEnabled": True,
    
    # Limits
    "azimuthMinLimit": 0,
    "azimuthMaxLimit": 450,
    "elevationMinLimit": 0,
    "elevationMaxLimit": 90,
    
    # Calibration
    "azimuthOffset": 0,
    "elevationOffset": 0,
    "azimuthScaleFactor": 1.0,
    "elevationScaleFactor": 1.0,
    "azimuthScaleFactorMin": 0.1,
    "azimuthScaleFactorMax": 2.0,
    "elevationScaleFactorMin": 0.1,
    "elevationScaleFactorMax": 2.0,
}

# INI file template with sections and comments
DEFAULT_INI_TEMPLATE = """; Rotor Control Configuration
; This file is automatically generated
; Settings are organized by category

[Connection]
; Serial port connection settings
baudRate=9600
pollingIntervalMs=1000

[Coordinates]
; Map display coordinates
mapLatitude=null
mapLongitude=null
satelliteMapEnabled=false
mapZoomLevel=15
mapZoomMin=5
mapZoomMax=25

[Cone]
; Cone visualization settings
coneAngle=10
coneLength=1000
azimuthDisplayOffset=0
coneAngleMin=1
coneAngleMax=90
coneLengthMin=0
coneLengthMax=100000
azimuthDisplayOffsetMin=-180
azimuthDisplayOffsetMax=180

[Speed]
; Rotor movement speeds in degrees per second
azimuthSpeedDegPerSec=4
elevationSpeedDegPerSec=2
speedMinDegPerSec=0.5
speedMaxDegPerSec=20

[Ramp]
; Softstart/Softstop PI controller settings
rampEnabled=true
rampKp=0.4
rampKi=0.05
rampSampleTimeMs=400
rampMaxStepDeg=8
rampToleranceDeg=1.5
rampKpMin=0
rampKpMax=5
rampKiMin=0
rampKiMax=5
rampSampleTimeMsMin=100
rampSampleTimeMsMax=2000
rampMaxStepDegMin=0.1
rampMaxStepDegMax=45
rampToleranceDegMin=0.1
rampToleranceDegMax=10

[Mode]
; Azimuth rotation mode
azimuthMode=450
elevationDisplayEnabled=true

[Limits]
; Soft limits for rotor movement
azimuthMinLimit=0
azimuthMaxLimit=450
elevationMinLimit=0
elevationMaxLimit=90

[Calibration]
; Calibration offsets and scaling factors
azimuthOffset=0
elevationOffset=0
azimuthScaleFactor=1.0
elevationScaleFactor=1.0
azimuthScaleFactorMin=0.1
azimuthScaleFactorMax=2.0
elevationScaleFactorMin=0.1
elevationScaleFactorMax=2.0
"""

