/**
 * INI File Handler
 * Handles reading and writing INI files both locally and via server
 */

class IniHandler {
  constructor() {
    this.iniFileName = 'rotor-config.ini';
    this.isFileProtocol = typeof window !== 'undefined' && window.location.protocol === 'file:';
    this.apiBase = window.location.origin;
  }

  /**
   * Get the path to the INI file
   * For file:// protocol, we'll try to use a relative path
   * For http/https, we'll use the server API
   */
  async getIniPath() {
    if (this.isFileProtocol) {
      // In file:// mode, try to use a relative path
      // The INI file should be in the same directory as the HTML file
      return this.iniFileName;
    } else {
      // In server mode, use API endpoint
      return `${this.apiBase}/api/config/ini`;
    }
  }

  /**
   * Parse INI file content into an object
   */
  parseIni(content) {
    const config = {};
    let currentSection = null;
    const lines = content.split(/\r?\n/);

    for (const line of lines) {
      const trimmed = line.trim();
      
      // Skip empty lines and comments
      if (!trimmed || trimmed.startsWith(';') || trimmed.startsWith('#')) {
        continue;
      }

      // Section header [section]
      const sectionMatch = trimmed.match(/^\[([^\]]+)\]$/);
      if (sectionMatch) {
        currentSection = sectionMatch[1];
        config[currentSection] = config[currentSection] || {};
        continue;
      }

      // Key=value pair
      const keyValueMatch = trimmed.match(/^([^=]+)=(.*)$/);
      if (keyValueMatch) {
        const key = keyValueMatch[1].trim();
        let value = keyValueMatch[2].trim();
        
        // Remove quotes if present
        if ((value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))) {
          value = value.slice(1, -1);
        }

        // Try to parse as number or boolean
        if (value === 'true') {
          value = true;
        } else if (value === 'false') {
          value = false;
        } else if (value === 'null' || value === '') {
          value = null;
        } else if (!isNaN(value) && value !== '') {
          // Check if it's a float or int
          value = value.includes('.') ? parseFloat(value) : parseInt(value, 10);
        }

        if (currentSection) {
          config[currentSection][key] = value;
        } else {
          config[key] = value;
        }
      }
    }

    return config;
  }

  /**
   * Convert config object to INI format
   */
  stringifyIni(config) {
    const sections = {
      'Connection': ['baudRate', 'pollingIntervalMs', 'simulation', 'connectionMode'],
      'Coordinates': ['mapLatitude', 'mapLongitude', 'satelliteMapEnabled'],
      'Cone': ['coneAngle', 'coneLength', 'azimuthDisplayOffset'],
      'Speed': ['azimuthSpeedDegPerSec', 'elevationSpeedDegPerSec'],
      'Ramp': ['rampEnabled', 'rampKp', 'rampKi', 'rampSampleTimeMs', 'rampMaxStepDeg', 'rampToleranceDeg'],
      'Mode': ['azimuthMode', 'elevationDisplayEnabled'],
      'Limits': ['azimuthMinLimit', 'azimuthMaxLimit', 'elevationMinLimit', 'elevationMaxLimit'],
      'Calibration': ['azimuthOffset', 'elevationOffset']
    };

    let ini = '; Rotor Control Configuration\n';
    ini += '; This file is automatically generated\n\n';

    for (const [sectionName, keys] of Object.entries(sections)) {
      ini += `[${sectionName}]\n`;
      for (const key of keys) {
        const value = config[key];
        if (value !== undefined && value !== null) {
          if (typeof value === 'string' && value.includes(',')) {
            ini += `${key}="${value}"\n`;
          } else {
            ini += `${key}=${value}\n`;
          }
        }
      }
      ini += '\n';
    }

    return ini;
  }

  /**
   * Load INI file
   */
  async load() {
    try {
      if (this.isFileProtocol) {
        // In file:// protocol, we cannot load files via fetch due to CORS restrictions
        // The INI file will be created when settings are saved, but we can't read it here
        // Fall back to localStorage in this case
        console.log('[IniHandler] file:// protocol detected - INI file loading not available, using localStorage');
        return null;
      } else {
        // Load via server API
        const response = await fetch(`${this.apiBase}/api/config/ini`, {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json'
          }
        });

        if (response.ok) {
          const data = await response.json();
          if (data.content) {
            const parsed = this.parseIni(data.content);
            console.log('[IniHandler] Successfully loaded INI file');
            return parsed;
          }
        } else if (response.status === 404) {
          // File doesn't exist yet, try to create default
          console.log('[IniHandler] INI file not found, will use defaults');
          return null;
        } else {
          console.warn('[IniHandler] Error loading INI file:', response.status, response.statusText);
        }
      }
    } catch (error) {
      console.warn('[IniHandler] Error loading INI file:', error);
      return null;
    }

    return null;
  }

  /**
   * Save INI file
   * NOTE: This method is not used anymore. INI file is read-only.
   * Settings are saved to localStorage only.
   */
  async save(config) {
    console.warn('[IniHandler] Save called but INI file is read-only. Use localStorage instead.');
    // INI file should be edited manually, not programmatically
    return false;
  }

  /**
   * Convert INI config to app config format
   */
  iniToConfig(iniConfig) {
    const config = {};
    
    // Flatten sections
    for (const sectionName in iniConfig) {
      if (typeof iniConfig[sectionName] === 'object' && !Array.isArray(iniConfig[sectionName])) {
        // It's a section
        Object.assign(config, iniConfig[sectionName]);
      } else {
        // It's a top-level key
        config[sectionName] = iniConfig[sectionName];
      }
    }

    return config;
  }

  /**
   * Convert app config to INI format (already handled by stringifyIni)
   */
  configToIni(config) {
    return this.stringifyIni(config);
  }
}

